#### Pandas Datastructure
- series- single dimensional datastructure: homogeneous
- Dataframe- multidimensional table: heterogeneous

In [71]:
import pandas as pd

In [72]:
ser1 = pd.Series([12,13,14], index=['A','b','c'])

print(ser1)

A    12
b    13
c    14
dtype: int64

In [73]:
calories = {
    'day1': 700,
    'day2': 2500,
    'day3': 1200
}

ser4 = pd.Series(calories, index=['day1','day2','day3'])
print(ser4)

day1     700
day2    2500
day3    1200
dtype: int64

In [74]:
fruit_data = {
    'apple_sales': [3, 2, 0, 2, 9, 4, 7, 2],
    'orange_sales': [0, 3, 2, 7, 7, 8, 3, 0 ]
}

purchases = pd.DataFrame(fruit_data, index=['Day1', 'Day2', 'Day3', 'Day4', 'Day5', 'Day6', 'Day7', 'Day8'])

print(purchases)

      apple_sales  orange_sales
Day1            3             0
Day2            2             3
Day3            0             2
Day4            2             7
Day5            9             7
Day6            4             8
Day7            7             3
Day8            2             0

In [75]:
edf = pd.read_csv('pandasLesson_data\data\employee.csv')
                  
edf.head()

<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\anabr\AppData\Local\Temp\ipykernel_10396\2457751164.py:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  edf = pd.read_csv('pandasLesson_data\data\employee.csv')

      Name   Age  Weight     Salary
0    James  36.0    75.0  5428000.0
1  Villers  38.0    74.0  3428000.0
2    VKole  31.0    70.0  8428000.0
3    Smith  34.0    80.0  4428000.0
4    Gayle  40.0   100.0  4528000.0

In [76]:
carsDf = pd.read_json(r'pandasLesson_data\data\cars.json')
carsDf.head()

carsDf.dtypes

Car                 str
MPG             float64
Cylinders         int64
Displacement    float64
Horsepower        int64
Weight            int64
Acceleration    float64
Model             int64
Origin              str
quantity          int64
city                str
dtype: object

In [77]:
#grab a specific record
carsDf.at[159, "MPG"]

carsDf.iat[159, 1]

carsDf.describe()

,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,quantity
count,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000
mean,23.801863,5.347826,185.232919,100.664596,2915.093168,15.509938,76.260870,224.875776
std,8.810125,1.761607,105.394809,41.079640,890.293883,2.515780,3.818576,127.741084
min,0.000000,3.000000,68.000000,0.000000,1613.000000,8.000000,70.000000,5.000000
25%,17.000000,4.000000,98.000000,72.000000,2130.000000,14.000000,73.000000,112.000000
50%,24.000000,4.000000,140.000000,88.000000,2625.000000,15.500000,76.000000,227.000000
75%,31.000000,8.000000,302.000000,130.000000,3620.000000,17.100000,80.000000,337.000000
max,46.600000,8.000000,440.000000,215.000000,4955.000000,22.100000,82.000000,439.000000

In [78]:
student_dict = {'Name': ['Joe', 'Nat', 'Harry'], 'Age': [20, 21, 19], 'Marks': [85.10, 77.80, 91.54]}

student_df = pd.DataFrame(student_dict)
print(student_df)
student_df.describe()

    Name  Age  Marks
0    Joe   20  85.10
1    Nat   21  77.80
2  Harry   19  91.54

        Age      Marks
count   3.0   3.000000
mean   20.0  84.813333
std     1.0   6.874484
min    19.0  77.800000
25%    19.5  81.450000
50%    20.0  85.100000
75%    20.5  88.320000
max    21.0  91.540000

In [79]:
list_index = student_df.columns
print('Col names', list_index)

Col names Index(['Name', 'Age', 'Marks'], dtype='str')

In [80]:
e_df = pd.read_csv(r'pandasLesson_data\data\employee.csv')

e_df.head(10)

e_df.tail(3)

tup = e_df.shape
print(tup)

rows, cols = e_df.shape
print(rows)
print(cols)

(15, 4)
15
4

In [81]:
df_cars = pd.read_json(r'pandasLesson_data\data\cars.json')
df_cars.head(5)

df_cars.columns[[0,3,5]]

df_cars[['Car','MPG']]

                            Car   MPG
0                Chevrolet Vega  25.0
1           Chevrolet Vega (sw)  22.0
2           Chevrolet Vega 2300  28.0
3               Chevrolet Woody  24.5
4    Chevrolete Chevelle Malibu  16.0
..                          ...   ...
156            Mercury Capri v6  21.0
157     Mercury Cougar Brougham  15.0
158       Mercury Grand Marquis  16.5
159              Mercury Lynx l  36.0
160             Mercury Marquis  11.0

[161 rows x 2 columns]

##### freqency analysis - value counts

In [82]:
# Sample DataFrame
data = {'Category': ['Electronics', 'Clothing', 'Electronics', 'Books', 'Books', 'Clothing']}

cat_df = pd.DataFrame(data)

cat_df.value_counts()

Category
Electronics    2
Clothing       2
Books          2
Name: count, dtype: int64

In [83]:
# Create the dataframe
sales_data={"Devices":['Laptop','iPhone','LED','LCD','Smart-Phone','Washing-Machine'],
           'Brand':['Lenovo','Apple','Samsung','Samsung','Samsung','Whirpool'],
           'Sales':[1000,2000,4000,2000,1000,4000],
           'Profit':[500,1000,1000,1500,1000,1500],
           'Pices left':[5000,4000,4000,5000,5000,1000]}

sales_df = pd.DataFrame(sales_data)
# get frequency count per brand
freq = sales_df['Brand'].value_counts()

freq_prd = freq[freq > 1].index[0]

print(freq)
print('item appears more than once:',freq_prd)

Brand
Samsung     3
Lenovo      1
Apple       1
Whirpool    1
Name: count, dtype: int64
item appears more than once: Samsung

In [84]:
data = {'Score' :[34, 57, 786, 23, 234, None, 45, 23]}
scores_df = pd.DataFrame(data)
score_count = scores_df.value_counts(dropna=False) # dropna, tells fucntion to eithr include or not incldue NaN, Null, NA values
print('Score', score_count)

Score Score
23.0     2
34.0     1
57.0     1
786.0    1
234.0    1
NaN      1
45.0     1
Name: count, dtype: int64

##### Rename a Column

In [85]:
tech = {
    'Courses': ["Python", ' DataAnalytics', 'MERN Stack', 'Data Engineering'],
    'Fee': [100, 2000, 250, 300],
    'Duration':['40days', '50days', '3 months', '1 year']
}

tech_df = pd.DataFrame(tech)

In [88]:
tech_df = tech_df.rename(columns={'Courses': 'Course Name'})
tech_df.head()

        Course Name   Fee  Duration
0            Python   100    40days
1     DataAnalytics  2000    50days
2        MERN Stack   250  3 months
3  Data Engineering   300    1 year