#### Pandas Datastructure
- series- single dimensional datastructure: homogeneous
- Dataframe- multidimensional table: heterogeneous

In [95]:
import pandas as pd
import numpy as np

In [96]:
ser1 = pd.Series([12,13,14], index=['A','b','c'])

print(ser1)

A    12
b    13
c    14
dtype: int64

In [97]:
calories = {
    'day1': 700,
    'day2': 2500,
    'day3': 1200
}

ser4 = pd.Series(calories, index=['day1','day2','day3'])
print(ser4)

day1     700
day2    2500
day3    1200
dtype: int64

In [98]:
fruit_data = {
    'apple_sales': [3, 2, 0, 2, 9, 4, 7, 2],
    'orange_sales': [0, 3, 2, 7, 7, 8, 3, 0 ]
}

purchases = pd.DataFrame(fruit_data, index=['Day1', 'Day2', 'Day3', 'Day4', 'Day5', 'Day6', 'Day7', 'Day8'])

print(purchases)

      apple_sales  orange_sales
Day1            3             0
Day2            2             3
Day3            0             2
Day4            2             7
Day5            9             7
Day6            4             8
Day7            7             3
Day8            2             0

In [99]:
edf = pd.read_csv('pandasLesson_data\data\employee.csv')
                  
edf.head()

<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\anabr\AppData\Local\Temp\ipykernel_22576\2457751164.py:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  edf = pd.read_csv('pandasLesson_data\data\employee.csv')

      Name   Age  Weight     Salary
0    James  36.0    75.0  5428000.0
1  Villers  38.0    74.0  3428000.0
2    VKole  31.0    70.0  8428000.0
3    Smith  34.0    80.0  4428000.0
4    Gayle  40.0   100.0  4528000.0

In [100]:
carsDf = pd.read_json(r'pandasLesson_data\data\cars.json')
carsDf.head()

carsDf.dtypes

Car                 str
MPG             float64
Cylinders         int64
Displacement    float64
Horsepower        int64
Weight            int64
Acceleration    float64
Model             int64
Origin              str
quantity          int64
city                str
dtype: object

In [101]:
#grab a specific record
carsDf.at[159, "MPG"]

carsDf.iat[159, 1]

carsDf.describe()

,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,quantity
count,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000
mean,23.801863,5.347826,185.232919,100.664596,2915.093168,15.509938,76.260870,224.875776
std,8.810125,1.761607,105.394809,41.079640,890.293883,2.515780,3.818576,127.741084
min,0.000000,3.000000,68.000000,0.000000,1613.000000,8.000000,70.000000,5.000000
25%,17.000000,4.000000,98.000000,72.000000,2130.000000,14.000000,73.000000,112.000000
50%,24.000000,4.000000,140.000000,88.000000,2625.000000,15.500000,76.000000,227.000000
75%,31.000000,8.000000,302.000000,130.000000,3620.000000,17.100000,80.000000,337.000000
max,46.600000,8.000000,440.000000,215.000000,4955.000000,22.100000,82.000000,439.000000

In [102]:
student_dict = {'Name': ['Joe', 'Nat', 'Harry'], 'Age': [20, 21, 19], 'Marks': [85.10, 77.80, 91.54]}

student_df = pd.DataFrame(student_dict)
print(student_df)
student_df.describe()

    Name  Age  Marks
0    Joe   20  85.10
1    Nat   21  77.80
2  Harry   19  91.54

        Age      Marks
count   3.0   3.000000
mean   20.0  84.813333
std     1.0   6.874484
min    19.0  77.800000
25%    19.5  81.450000
50%    20.0  85.100000
75%    20.5  88.320000
max    21.0  91.540000

In [103]:
list_index = student_df.columns
print('Col names', list_index)

Col names Index(['Name', 'Age', 'Marks'], dtype='str')

In [104]:
e_df = pd.read_csv(r'pandasLesson_data\data\employee.csv')

e_df.head(10)

e_df.tail(3)

tup = e_df.shape
print(tup)

rows, cols = e_df.shape
print(rows)
print(cols)

(15, 4)
15
4

In [105]:
df_cars = pd.read_json(r'pandasLesson_data\data\cars.json')
df_cars.head(5)

df_cars.columns[[0,3,5]]

df_cars[['Car','MPG']]

                            Car   MPG
0                Chevrolet Vega  25.0
1           Chevrolet Vega (sw)  22.0
2           Chevrolet Vega 2300  28.0
3               Chevrolet Woody  24.5
4    Chevrolete Chevelle Malibu  16.0
..                          ...   ...
156            Mercury Capri v6  21.0
157     Mercury Cougar Brougham  15.0
158       Mercury Grand Marquis  16.5
159              Mercury Lynx l  36.0
160             Mercury Marquis  11.0

[161 rows x 2 columns]

##### freqency analysis - value counts

In [106]:
# Sample DataFrame
data = {'Category': ['Electronics', 'Clothing', 'Electronics', 'Books', 'Books', 'Clothing']}

cat_df = pd.DataFrame(data)

cat_df.value_counts()

Category
Electronics    2
Clothing       2
Books          2
Name: count, dtype: int64

In [107]:
# Create the dataframe
sales_data={"Devices":['Laptop','iPhone','LED','LCD','Smart-Phone','Washing-Machine'],
           'Brand':['Lenovo','Apple','Samsung','Samsung','Samsung','Whirpool'],
           'Sales':[1000,2000,4000,2000,1000,4000],
           'Profit':[500,1000,1000,1500,1000,1500],
           'Pices left':[5000,4000,4000,5000,5000,1000]}

sales_df = pd.DataFrame(sales_data)
# get frequency count per brand
freq = sales_df['Brand'].value_counts()

freq_prd = freq[freq > 1].index[0]

print(freq)
print('item appears more than once:',freq_prd)

Brand
Samsung     3
Lenovo      1
Apple       1
Whirpool    1
Name: count, dtype: int64
item appears more than once: Samsung

In [108]:
data = {'Score' :[34, 57, 786, 23, 234, None, 45, 23]}
scores_df = pd.DataFrame(data)
score_count = scores_df.value_counts(dropna=False) # dropna, tells fucntion to eithr include or not incldue NaN, Null, NA values
print('Score', score_count)

Score Score
23.0     2
34.0     1
57.0     1
786.0    1
234.0    1
NaN      1
45.0     1
Name: count, dtype: int64

##### Rename a Column

In [109]:
tech = {
    'Courses': ["Python", ' DataAnalytics', 'MERN Stack', 'Data Engineering'],
    'Fee': [100, 2000, 250, 300],
    'Duration':['40days', '50days', '3 months', '1 year']
}

tech_df = pd.DataFrame(tech)

In [110]:
tech_df = tech_df.rename(columns={'Courses': 'Course Name'})
tech_df.head()

        Course Name   Fee  Duration
0            Python   100    40days
1     DataAnalytics  2000    50days
2        MERN Stack   250  3 months
3  Data Engineering   300    1 year

#### Sorting Asc and Dsc
##### by one column
##### by many columns

In [111]:
cars =pd.read_json(r'pandasLesson_data\data\cars.json')

cars.sort_values(by= 'quantity', ascending=True)
cars.sort_values(by= ['quantity', 'Cylinders'], ascending=[True, False])

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
123,Ford Torino,17.0,8,302.0,140,3449,10.5,70,US,5,OH
112,Ford Mustang II 2+2,25.5,4,140.0,89,2755,15.8,77,US,5,NJ
7,Chrysler Cordoba,15.5,8,400.0,190,4325,12.2,77,US,7,NJ
6,Chevy S-10,31.0,4,119.0,82,2720,19.4,82,US,7,NewYork
121,Ford Ranger,28.0,4,120.0,79,2625,18.6,82,US,7,DALLAS
...,...,...,...,...,...,...,...,...,...,...,...
128,Honda Accord,36.0,4,107.0,75,2205,14.5,82,Japan,427,OH
134,Honda Civic (auto),32.0,4,91.0,67,1965,15.7,82,Japan,430,TEXAS
22,Datsun 310 GX,38.0,4,91.0,67,1995,16.2,82,Japan,431,NJ
8,Chrysler Lebaron Medallion,26.0,4,156.0,92,2585,14.5,82,US,434,DALLAS
110,Ford Mustang GL,27.0,4,140.0,86,2790,15.6,82,US,439,OH

#### Slicing a DF with .iloc[] and .loc[]

In [112]:
# Initializing the nested list with Data set
employee_list = [['James', 36, 75, 5428000],
               ['Villers', 38, 74, 3428000],
               ['VKole', 31, 70, 8428000],
               ['Smith', 34, 80, 4428000],
               ['Gayle', 40, 100, 4528000],
               ['Rooter', 33, 72, 7028000],
               ['Peterson', 42, 85, 2528000],
               ['John', 41, 85, 1528000],

]

e_df = pd.DataFrame(employee_list, columns=['Names', 'Age','Weight','Salary'])
e_df.head()

     Names  Age  Weight   Salary
0    James   36      75  5428000
1  Villers   38      74  3428000
2    VKole   31      70  8428000
3    Smith   34      80  4428000
4    Gayle   40     100  4528000

In [113]:
# grab the first row
e_df.iloc[:1]

   Names  Age  Weight   Salary
0  James   36      75  5428000

In [114]:
# grab all rows, but only the first 3 columns
e_df.iloc[ : , :3]

      Names  Age  Weight
0     James   36      75
1   Villers   38      74
2     VKole   31      70
3     Smith   34      80
4     Gayle   40     100
5    Rooter   33      72
6  Peterson   42      85
7      John   41      85

In [115]:
basketball = {'team': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'],
                   'points': [18, 22, 19, 14, 14, 11, 20, 28],
                   'assists': [5, 7, 7, 9, 12, 9, 9, 4],
                   'rebounds': [11, 8, 10, 6, 6, 5, 9, 12],
                   'steals': [4, 3, 3, 2, 5, 4, 3, 8],
                   'blocks': [1, 0, 0, 3, 2, 2, 1, 5]}

ball_up = pd.DataFrame(basketball)

In [116]:
ball_up.head()

  team  points  assists  rebounds  steals  blocks
0    A      18        5        11       4       1
1    B      22        7         8       3       0
2    C      19        7        10       3       0
3    D      14        9         6       2       3
4    E      14       12         6       5       2

In [117]:
#locate all rows an dcolumns teams, rebounds
ball_up.loc[:, ['team', 'rebounds']]

  team  rebounds
0    A        11
1    B         8
2    C        10
3    D         6
4    E         6
5    F         5
6    G         9
7    H        12

In [118]:
#select values from rows 3-6 and show the team name
ball_up.loc[3:6, ['team']]

  team
3    D
4    E
5    F
6    G

#### Handling Missing Values
`df.isnull()`
`df.fillna()`
`df.dropna()`
`df.replace()`

#### Pandas Date Time

In [139]:
date_range = pd.date_range(start='04/01/2026', end='05/05/2026', periods=7)

date_range

DatetimeIndex(['2026-04-01 00:00:00', '2026-04-06 16:00:00',
               '2026-04-12 08:00:00', '2026-04-18 00:00:00',
               '2026-04-23 16:00:00', '2026-04-29 08:00:00',
               '2026-05-05 00:00:00'],
              dtype='datetime64[us]', freq=None)

In [140]:
date_ran = pd.date_range(start='01/01/2020', end='05/05/2026', freq='YE')
date_ran

DatetimeIndex(['2020-12-31', '2021-12-31', '2022-12-31', '2023-12-31',
               '2024-12-31', '2025-12-31'],
              dtype='datetime64[us]', freq='YE-DEC')

In [141]:
date_ran2 = pd.date_range(start='01/01/2020', periods=6, tz='Asia/Tokyo')
date_ran2

DatetimeIndex(['2020-01-01 00:00:00+09:00', '2020-01-02 00:00:00+09:00',
               '2020-01-03 00:00:00+09:00', '2020-01-04 00:00:00+09:00',
               '2020-01-05 00:00:00+09:00', '2020-01-06 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Tokyo]', freq='D')

In [142]:
start_date = '01/01/2023' 
num = 30

date_ran3 = pd.date_range(start=start_date, periods=num, freq='D')
np.random.seed(42)

ranGen = np.random.normal(loc=100, scale=5, size=num).round(2)

ranGen1 = pd.DataFrame({'Date': date_ran3, 'StockPrice': ranGen})

ranGen1

         Date  StockPrice
0  2023-01-01      102.48
1  2023-01-02       99.31
2  2023-01-03      103.24
3  2023-01-04      107.62
4  2023-01-05       98.83
5  2023-01-06       98.83
6  2023-01-07      107.90
7  2023-01-08      103.84
8  2023-01-09       97.65
9  2023-01-10      102.71
10 2023-01-11       97.68
11 2023-01-12       97.67
12 2023-01-13      101.21
13 2023-01-14       90.43
14 2023-01-15       91.38
15 2023-01-16       97.19
16 2023-01-17       94.94
17 2023-01-18      101.57
18 2023-01-19       95.46
19 2023-01-20       92.94
20 2023-01-21      107.33
21 2023-01-22       98.87
22 2023-01-23      100.34
23 2023-01-24       92.88
24 2023-01-25       97.28
25 2023-01-26      100.55
26 2023-01-27       94.25
27 2023-01-28      101.88
28 2023-01-29       97.00
29 2023-01-30       98.54

In [143]:
import datetime

timestamp = pd.Timestamp('2026-05-05 12:38:00')
print(timestamp)


dt_timestamp = datetime.datetime(2026, 5, 5, 13, 38)
print(dt_timestamp)

2026-05-05 12:38:00
2026-05-05 13:38:00

In [144]:
timestamp.year

2026

In [145]:

df = pd.DataFrame({
    'patientID':[101,23,48,49],
    'name': ['alice','bob','charlie','Eric'],
    'date_of_birth': ['2023-01-01', '2023-01-02', '3/10/2020 143045', '13th of October, 2023']
})

df.info

<bound method DataFrame.info of    patientID     name          date_of_birth
0        101    alice             2023-01-01
1         23      bob             2023-01-02
2         48  charlie       3/10/2020 143045
3         49     Eric  13th of October, 2023>

In [146]:
df['date_of_birth'].dtype

In [147]:
df['date_of_birth'] = pd.to_datetime(df['date_of_birth'], format='mixed')
print(df)

   patientID     name       date_of_birth
0        101    alice 2023-01-01 00:00:00
1         23      bob 2023-01-02 00:00:00
2         48  charlie 2020-03-10 14:30:45
3         49     Eric 2023-10-13 00:00:00

In [148]:
df = pd.DataFrame({
    'patientID':[101,23,48,49],
    'name': ['alice','bob','charlie','keyla'],
    'date_of_birth': ['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04']
})

df['date_of_birth'] = pd.to_datetime(df['date_of_birth'], format= 'mixed', errors='coerce')
df

   patientID     name date_of_birth
0        101    alice    2023-01-01
1         23      bob    2023-01-02
2         48  charlie    2023-01-03
3         49    keyla    2023-01-04

In [149]:
url='https://raw.githubusercontent.com/bprasad26/lwd/master/data/tesla_stock_prices.csv'

turl='https://raw.githubusercontent.com/bprasad26/lwd/master/data/tesla_stock_prices.csv'
# using parse_dates to change type from string into date
tesla_df = pd.read_csv(url, parse_dates=['Date'])
# tesla_df.to_csv('data/tesla_stocks.csv')
tesla_df.head()
# tesla_df.info()

        Date       Open   High        Low      Close  Adj Close    Volume
0 2010-06-29  19.000000  25.00  17.540001  23.889999  23.889999  18766300
1 2010-06-30  25.790001  30.42  23.299999  23.830000  23.830000  17187100
2 2010-07-01  25.000000  25.92  20.270000  21.959999  21.959999   8218800
3 2010-07-02  23.000000  23.10  18.709999  19.200001  19.200001   5139800
4 2010-07-06  20.000000  20.00  15.830000  16.110001  16.110001   6866900

In [150]:
# add new column to dateframe based of of dates
# Add new columns to dataframe based off of dates
tesla_df['Day'] = tesla_df['Date'].dt.day
tesla_df['Month'] = tesla_df['Date'].dt.month
tesla_df['Year'] = tesla_df['Date'].dt.year
tesla_df['day_name'] = tesla_df['Date'].dt.day_name()

tesla_df.head(10)

,Date,Open,High,Low,Close,Adj Close,Volume,Day,Month,Year,day_name
0,2010-06-29,19.000000,25.000000,17.540001,23.889999,23.889999,18766300,29,6,2010,Tuesday
1,2010-06-30,25.790001,30.420000,23.299999,23.830000,23.830000,17187100,30,6,2010,Wednesday
2,2010-07-01,25.000000,25.920000,20.270000,21.959999,21.959999,8218800,1,7,2010,Thursday
3,2010-07-02,23.000000,23.100000,18.709999,19.200001,19.200001,5139800,2,7,2010,Friday
4,2010-07-06,20.000000,20.000000,15.830000,16.110001,16.110001,6866900,6,7,2010,Tuesday
5,2010-07-07,16.400000,16.629999,14.980000,15.800000,15.800000,6921700,7,7,2010,Wednesday
6,2010-07-08,16.139999,17.520000,15.570000,17.459999,17.459999,7711400,8,7,2010,Thursday
7,2010-07-09,17.580000,17.900000,16.549999,17.400000,17.400000,4050600,9,7,2010,Friday
8,2010-07-12,17.950001,18.070000,17.000000,17.049999,17.049999,2202500,12,7,2010,Monday
9,2010-07-13,17.389999,18.639999,16.900000,18.139999,18.139999,2680100,13,7,2010,Tuesday

In [151]:
#grab max and min:
most_recent = tesla_df['Date'].min()
least_recent = tesla_df['Date'].max()
print(most_recent)
least_recent

2010-06-29 00:00:00

Timestamp('2017-08-08 00:00:00')

In [152]:
monthly_sales = tesla_df.groupby(['Year','Month'])['Volume'].sum().reset_index()

monthly_sales.head(15)

    Year  Month    Volume
0   2010      6  35953400
1   2010      7  64575800
2   2010      8  15038200
3   2010      9  18045900
4   2010     10   6547800
5   2010     11  28315100
6   2010     12  36892900
7   2011      1  28420100
8   2011      2  29303500
9   2011      3  32563300
10  2011      4  29894900
11  2011      5  30348800
12  2011      6  39727300
13  2011      7  21102100
14  2011      8  27215700

##### Filter using loc[] or query[]

In [154]:
fil_df_date = tesla_df.loc[(tesla_df['Date'] >= '2010-08-01')]

fil_df_date

,Date,Open,High,Low,Close,Adj Close,Volume,Day,Month,Year,day_name
23,2010-08-02,20.500000,20.969999,20.330000,20.920000,20.920000,718100,2,8,2010,Monday
24,2010-08-03,21.000000,21.950001,20.820000,21.950001,21.950001,1230500,3,8,2010,Tuesday
25,2010-08-04,21.950001,22.180000,20.850000,21.260000,21.260000,913000,4,8,2010,Wednesday
26,2010-08-05,21.540001,21.549999,20.049999,20.450001,20.450001,796200,5,8,2010,Thursday
27,2010-08-06,20.100000,20.160000,19.520000,19.590000,19.590000,741900,6,8,2010,Friday
...,...,...,...,...,...,...,...,...,...,...,...
1786,2017-08-02,318.940002,327.119995,311.220001,325.890015,325.890015,13091500,2,8,2017,Wednesday
1787,2017-08-03,345.329987,350.000000,343.149994,347.089996,347.089996,13535000,3,8,2017,Thursday
1788,2017-08-04,347.000000,357.269989,343.299988,356.910004,356.910004,9198400,4,8,2017,Friday
1789,2017-08-07,357.350006,359.480011,352.750000,355.170013,355.170013,6276900,7,8,2017,Monday
1790,2017-08-08,357.529999,368.579987,357.399994,365.220001,365.220001,7449837,8,8,2017,Tuesday

In [156]:
fil_df_date2 = tesla_df.loc[(tesla_df['Date'] >= '2010-08-01') & (tesla_df['Date'] <= '2010-12-31')]
fil_df_date2

,Date,Open,High,Low,Close,Adj Close,Volume,Day,Month,Year,day_name
23,2010-08-02,20.500000,20.969999,20.330000,20.920000,20.920000,718100,2,8,2010,Monday
24,2010-08-03,21.000000,21.950001,20.820000,21.950001,21.950001,1230500,3,8,2010,Tuesday
25,2010-08-04,21.950001,22.180000,20.850000,21.260000,21.260000,913000,4,8,2010,Wednesday
26,2010-08-05,21.540001,21.549999,20.049999,20.450001,20.450001,796200,5,8,2010,Thursday
27,2010-08-06,20.100000,20.160000,19.520000,19.590000,19.590000,741900,6,8,2010,Friday
...,...,...,...,...,...,...,...,...,...,...,...
125,2010-12-27,28.020000,28.580000,25.059999,25.549999,25.549999,9301900,27,12,2010,Monday
126,2010-12-28,25.850000,26.750000,25.000000,26.410000,26.410000,4056300,28,12,2010,Tuesday
127,2010-12-29,27.030001,28.010000,26.500000,27.730000,27.730000,3319200,29,12,2010,Wednesday
128,2010-12-30,27.700001,27.900000,26.379999,26.500000,26.500000,2041100,30,12,2010,Thursday
129,2010-12-31,26.570000,27.250000,26.500000,26.629999,26.629999,1417900,31,12,2010,Friday

In [158]:
fil_df = tesla_df.query("Date >= '2010-08-01' and Date <= '2010-12-31'")
fil_df

,Date,Open,High,Low,Close,Adj Close,Volume,Day,Month,Year,day_name
23,2010-08-02,20.500000,20.969999,20.330000,20.920000,20.920000,718100,2,8,2010,Monday
24,2010-08-03,21.000000,21.950001,20.820000,21.950001,21.950001,1230500,3,8,2010,Tuesday
25,2010-08-04,21.950001,22.180000,20.850000,21.260000,21.260000,913000,4,8,2010,Wednesday
26,2010-08-05,21.540001,21.549999,20.049999,20.450001,20.450001,796200,5,8,2010,Thursday
27,2010-08-06,20.100000,20.160000,19.520000,19.590000,19.590000,741900,6,8,2010,Friday
...,...,...,...,...,...,...,...,...,...,...,...
125,2010-12-27,28.020000,28.580000,25.059999,25.549999,25.549999,9301900,27,12,2010,Monday
126,2010-12-28,25.850000,26.750000,25.000000,26.410000,26.410000,4056300,28,12,2010,Tuesday
127,2010-12-29,27.030001,28.010000,26.500000,27.730000,27.730000,3319200,29,12,2010,Wednesday
128,2010-12-30,27.700001,27.900000,26.379999,26.500000,26.500000,2041100,30,12,2010,Thursday
129,2010-12-31,26.570000,27.250000,26.500000,26.629999,26.629999,1417900,31,12,2010,Friday